version: "3.7"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - "27018:27018"
